START TRANSACTION;

-- --------------------------------------------------------
-- INSERIMENTO UTENTI E CLIENTI (DA CSV UNIBO)
-- Password: $2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6
-- --------------------------------------------------------

-- Esempio per i primi record (procedura ripetuta per tutti)

INSERT INTO `utenti` (`email`, `password`, `mensa`, `cliente`) VALUES
('simone.alocchi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('davide.amantini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('enrico.ancarani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('manuel.andruccioli@unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.antonioli2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('kelly.applebee@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('eric.aquilotti2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.aresu2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giuseppe.argentiere@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('manuel.aveta@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('hamail.azhar@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('stefano.baiano@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('riccardo.ballan@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.bandini5@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('enrico.bartocetti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('eleonora.bartoletti2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alan.barzanti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('vittoria.barzanti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('ciro.bassi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.battistini10@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alice.beccati@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('manuel.benagli@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicholas.benedetti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.benzi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('laura.bertozzi5@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('samuele.bianchedi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('eleonora.bianco3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.bisulli@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('samuele.bizzocchi3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.boccuzzi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('grazia.bochdanovits@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('irene.borri@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.botteghi6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('riem.boukhama@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simone.brunelli3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.bulfoni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.bulgarelli6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simoneandres.caguana@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simone.capacci3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('justin.carideo@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('riccardo.carta2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.caruso7@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('enrico.casadei18@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.casadei16@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alex.casadio3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.casali13@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('michele.casamenti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giuseppe.cattolico@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('mattia.cavina2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.ceccarelli12@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('aya.chbraoui@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.chierici2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('livia.cicognani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('flavio.ciliberti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sofia.cipollone@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marko.cobo@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('riccardo.cornacchia@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.crepaldi4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('ivan.crimaldi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('vincenzo.daidone@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.dallara2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('leonardo.damario@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('samuele.dambrosio2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('mattia.daviducci@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.debertolis@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.dellasantina@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('arianna.delmese@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giovanni.delnevo@unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('adis.dema@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('paolo.demori@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.detommaso@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('cristian.didonato@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('stefano.distefano3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('karim.elberni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('saad.elmaliki@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nizar.elyaakoubi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alion.emini2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.fabbri53@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('emanuele.fabricat@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.fagioli4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('zhiheng.fan2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giulia.fares@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giorgia.fernandez@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alice.ferri8@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.ferri21@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('gioele.foschi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('paolo.foschini2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('filippo.francalanci@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('andrea.fronzi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('elena.fucci3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simone.furcas@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giuseppe.fusco9@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.gardini7@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesca.gatti15@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simone.gentili4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('frances.giancaterin2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.goni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.grandini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('filippo.greppi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('fabio.gruppioni2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicholas.guerra@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('eugenio.guidi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('kirollosemad.habashi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('daniel.horna@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('chengzhou.hu@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('christian.kadiu@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('paulo.kravchuk@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('andrea.latosa@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lucasantonio.leonte@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luigi.linari@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('claudio.lodi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sebastiano.lucarelli@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('jonathan.lupini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicholas.magi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('davideandrea.magyari@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('martina.malagoli4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.maldini4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('elia.mami@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('davide.mancini10@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicolas.mancini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.manfroni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('federico.mantoni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.marchegiani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('pietro.maretti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('federico.mariani3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matilde.mariani3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('raffaele.marrazzo@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessia.marzano@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('simone.mazzacano2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicola.mazzotti7@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('max.melandri@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesco.meloni6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('leonardo.meloni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('filippo.merlini2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessio.minniti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.miraglia@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('silvia.mirri@unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.monari6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.mondardini2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('elena.montalti5@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicolas.montanari3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('andrea.monti24@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('mattia.mularoni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('arthuristvan.muller@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('vera.murgia@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('cristofer.napolitano@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('carlo.nicastro2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.nori@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('maisam.noumi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('kelvin.olaiya@unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('pietro.olivi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('antonio.olmeda@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.onofri4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sohaib.ouakani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('federico.panzavolta@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.pasini14@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('filippo.patrignani2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giovanni.perreon@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('leonardo.perretta2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marco.pertegato@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesco.petrassi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('andrew.pierpaolini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('stefano.pinza@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('ilaria.piras2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lucia.pola@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.porcheddu@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('mattia.pozzati3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesco.prandini3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('maddalena.prandini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.prati3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lucas.prati@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.pulga@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessio.pulzoni@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('kangzhe.qiu@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('cristian.qorri@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('thirumavija.ramasamy@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('vincentrey.ramos@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('gabriele.ranzari@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giovannimaria.rava@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.ravaioli8@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('martina.ravaioli6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('adampaolo.razzino@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.rebosio@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('andrea.reggiani14@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicholas.ricci3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('filippo.ricciotti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sofia.ricupero@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('valentina.rigato@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('mattia.rocchi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('davide.rossi47@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lorenzo.rossi50@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.sacchetti4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesco.sacripante@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('jonathan.salvetti@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('patricia.sanchez4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.santarelli6@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('valerii.sargov@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('rebecca.scarcelli@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('edoardo.scorza@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('yue.shen@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('pietro.siboni3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('miriam.sonaglia@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('hiba.soufi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('ettore.spaccini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('marcello.spagnoli2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('gianmarco.spinaci3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('ludovico.spitaleri@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('francesco.stortini@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sabrina.tassinari@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('nicolas.tazzieri@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tchakoute.odile@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('giada.tedaldi@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('alessandro.testa9@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.todeschi2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.tonelli8@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('caterina.torelli2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('riccardo.traini3@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('daniele.tramonti2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('samuele.trapani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('gianni.tumedei2@unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('egor.tverdohleb@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.valentini2@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('tommaso.valeriani@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.varalerolla@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('carmine.varipapa@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('elettra.ventura@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('luca.venturi29@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('valeria.verde@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('davide.vignali4@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('sara.visani7@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lassejoi.werpers@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('lukasz.wojnicz@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1),
('matteo.zoli7@studio.unibo.it', '$2y$10$3Qz0XnIIJEEcxRU2ferNM.w9IRxH2jcGlYa4bXMq1kfW/yjfEecM6', 0, 1);

-- --------------------------------------------------------
-- INSERIMENTO DETTAGLI ANAGRAFICI NELLA TABELLA CLIENTI
-- --------------------------------------------------------

INSERT INTO `clienti` (`email`, `nome`, `cognome`) VALUES
('simone.alocchi@studio.unibo.it', 'Simone', 'Alocchi'),
('davide.amantini@studio.unibo.it', 'Davide', 'Amantini'),
('enrico.ancarani@studio.unibo.it', 'Enrico', 'Ancarani'),
('manuel.andruccioli@unibo.it', 'Manuel', 'Andruccioli'),
('lorenzo.antonioli2@studio.unibo.it', 'Lorenzo', 'Antonioli'),
('kelly.applebee@studio.unibo.it', 'Kelly', 'Applebee'),
('eric.aquilotti2@studio.unibo.it', 'Eric', 'Aquilotti'),
('marco.aresu2@studio.unibo.it', 'Marco', 'Aresu'),
('giuseppe.argentiere@studio.unibo.it', 'Giuseppe', 'Argentiere'),
('manuel.aveta@studio.unibo.it', 'Manuel', 'Aveta'),
('hamail.azhar@studio.unibo.it', 'Hamail', 'Azhar'),
('stefano.baiano@studio.unibo.it', 'Stefano', 'Baiano'),
('riccardo.ballan@studio.unibo.it', 'Riccardo', 'Ballan'),
('tommaso.bandini5@studio.unibo.it', 'Tommaso', 'Bandini'),
('enrico.bartocetti@studio.unibo.it', 'Enrico', 'Bartocetti'),
('eleonora.bartoletti2@studio.unibo.it', 'Eleonora', 'Bartoletti'),
('alan.barzanti@studio.unibo.it', 'Alan', 'Barzanti'),
('vittoria.barzanti@studio.unibo.it', 'Vittoria', 'Barzanti'),
('ciro.bassi@studio.unibo.it', 'Ciro', 'Bassi'),
('marco.battistini10@studio.unibo.it', 'Marco', 'Battistini'),
('alice.beccati@studio.unibo.it', 'Alice', 'Beccati'),
('manuel.benagli@studio.unibo.it', 'Manuel', 'Benagli'),
('nicholas.benedetti@studio.unibo.it', 'Nicholas', 'Benedetti'),
('luca.benzi2@studio.unibo.it', 'Luca', 'Benzi'),
('laura.bertozzi5@studio.unibo.it', 'Laura', 'Bertozzi'),
('samuele.bianchedi@studio.unibo.it', 'Samuele', 'Bianchedi'),
('eleonora.bianco3@studio.unibo.it', 'Eleonora', 'Bianco'),
('tommaso.bisulli@studio.unibo.it', 'Tommaso', 'Bisulli'),
('samuele.bizzocchi3@studio.unibo.it', 'Samuele', 'Bizzocchi'),
('lorenzo.boccuzzi@studio.unibo.it', 'Lorenzo', 'Boccuzzi'),
('grazia.bochdanovits@studio.unibo.it', 'Grazia', 'Bochdanovits De Kavna'),
('irene.borri@studio.unibo.it', 'Irene', 'Borri'),
('matteo.botteghi6@studio.unibo.it', 'Matteo', 'Botteghi'),
('riem.boukhama@studio.unibo.it', 'Riem', 'Boukhama'),
('simone.brunelli3@studio.unibo.it', 'Simone', 'Brunelli'),
('lorenzo.bulfoni@studio.unibo.it', 'Lorenzo', 'Bulfoni'),
('marco.bulgarelli6@studio.unibo.it', 'Marco', 'Bulgarelli'),
('simoneandres.caguana@studio.unibo.it', 'Simone Andres', 'Caguana Barrios'),
('simone.capacci3@studio.unibo.it', 'Simone', 'Capacci'),
('justin.carideo@studio.unibo.it', 'Justin', 'Carideo'),
('riccardo.carta2@studio.unibo.it', 'Riccardo', 'Carta'),
('matteo.caruso7@studio.unibo.it', 'Matteo', 'Caruso'),
('enrico.casadei18@studio.unibo.it', 'Enrico', 'Casadei'),
('lorenzo.casadei16@studio.unibo.it', 'Lorenzo', 'Casadei'),
('alex.casadio3@studio.unibo.it', 'Alex', 'Casadio'),
('marco.casali13@studio.unibo.it', 'Marco', 'Casali'),
('michele.casamenti@studio.unibo.it', 'Michele', 'Casamenti'),
('giuseppe.cattolico@studio.unibo.it', 'Giuseppe', 'Cattolico'),
('mattia.cavina2@studio.unibo.it', 'Mattia', 'Cavina'),
('matteo.ceccarelli12@studio.unibo.it', 'Matteo', 'Ceccarelli'),
('aya.chbraoui@studio.unibo.it', 'Aya', 'Chbraoui'),
('alessandro.chierici2@studio.unibo.it', 'Alessandro', 'Chierici'),
('livia.cicognani@studio.unibo.it', 'Livia', 'Cicognani'),
('flavio.ciliberti@studio.unibo.it', 'Flavio', 'Ciliberti'),
('sofia.cipollone@studio.unibo.it', 'Sofia', 'Cipollone'),
('marko.cobo@studio.unibo.it', 'Marko', 'Cobo'),
('riccardo.cornacchia@studio.unibo.it', 'Riccardo', 'Cornacchia'),
('matteo.crepaldi4@studio.unibo.it', 'Matteo', 'Crepaldi'),
('ivan.crimaldi@studio.unibo.it', 'Ivan', 'Crimaldi'),
('vincenzo.daidone@studio.unibo.it', 'Vincenzo', 'Daidone'),
('lorenzo.dallara2@studio.unibo.it', 'Lorenzo', 'Dall''Ara'),
('leonardo.damario@studio.unibo.it', 'Leonardo', 'D''Amario'),
('samuele.dambrosio2@studio.unibo.it', 'Samuele', 'D''Ambrosio'),
('mattia.daviducci@studio.unibo.it', 'Mattia', 'Daviducci'),
('lorenzo.debertolis@studio.unibo.it', 'Lorenzo', 'Debertolis'),
('luca.dellasantina@studio.unibo.it', 'Luca', 'Dellasantina'),
('arianna.delmese@studio.unibo.it', 'Arianna', 'Del Mese'),
('giovanni.delnevo@unibo.it', 'Giovanni', 'Delnevo'),
('adis.dema@studio.unibo.it', 'Adis', 'Dema'),
('paolo.demori@studio.unibo.it', 'Paolo', 'De Mori'),
('tommaso.detommaso@studio.unibo.it', 'Tommaso', 'De Tommaso'),
('cristian.didonato@studio.unibo.it', 'Cristian', 'Di Donato'),
('stefano.distefano3@studio.unibo.it', 'Stefano', 'Distefano'),
('karim.elberni@studio.unibo.it', 'Karim', 'El Berni'),
('saad.elmaliki@studio.unibo.it', 'Saad', 'El Maliki'),
('nizar.elyaakoubi@studio.unibo.it', 'Nizar', 'El Yaakoubi'),
('alion.emini2@studio.unibo.it', 'Alion', 'Emini'),
('luca.fabbri53@studio.unibo.it', 'Luca', 'Fabbri'),
('emanuele.fabricat@studio.unibo.it', 'Emanuele', 'Fabricat'),
('luca.fagioli4@studio.unibo.it', 'Luca', 'Fagioli'),
('zhiheng.fan2@studio.unibo.it', 'Zhiheng', 'Fan'),
('giulia.fares@studio.unibo.it', 'Giulia', 'Fares'),
('giorgia.fernandez@studio.unibo.it', 'Giorgia', 'Fernandez'),
('alice.ferri8@studio.unibo.it', 'Alice', 'Ferri'),
('lorenzo.ferri21@studio.unibo.it', 'Lorenzo', 'Ferri'),
('gioele.foschi@studio.unibo.it', 'Gioele', 'Foschi'),
('paolo.foschini2@studio.unibo.it', 'Paolo', 'Foschini'),
('filippo.francalanci@studio.unibo.it', 'Filippo', 'Francalanci'),
('andrea.fronzi@studio.unibo.it', 'Andrea', 'Fronzi'),
('elena.fucci3@studio.unibo.it', 'Elena', 'Fucci'),
('simone.furcas@studio.unibo.it', 'Simone', 'Furcas'),
('giuseppe.fusco9@studio.unibo.it', 'Giuseppe', 'Fusco'),
('alessandro.gardini7@studio.unibo.it', 'Alessandro', 'Gardini'),
('francesca.gatti15@studio.unibo.it', 'Francesca', 'Gatti'),
('simone.gentili4@studio.unibo.it', 'Simone', 'Gentili'),
('frances.giancaterin2@studio.unibo.it', 'Francesco', 'Giancaterino'),
('tommaso.goni@studio.unibo.it', 'Tommaso', 'Goni'),
('matteo.grandini@studio.unibo.it', 'Matteo', 'Grandini'),
('filippo.greppi2@studio.unibo.it', 'Filippo', 'Greppi'),
('fabio.gruppioni2@studio.unibo.it', 'Fabio', 'Gruppioni'),
('nicholas.guerra@studio.unibo.it', 'Nicholas', 'Guerra'),
('eugenio.guidi@studio.unibo.it', 'Eugenio', 'Guidi'),
('kirollosemad.habashi@studio.unibo.it', 'Kirollos Emad Salib', 'Habashi'),
('daniel.horna@studio.unibo.it', 'Daniel Alejandro', 'Horna'),
('chengzhou.hu@studio.unibo.it', 'Chengzhou', 'Hu'),
('christian.kadiu@studio.unibo.it', 'Christian', 'Kadiu'),
('paulo.kravchuk@studio.unibo.it', 'Paulo', 'Kravchuk'),
('andrea.latosa@studio.unibo.it', 'Andrea', 'La Tosa'),
('lucasantonio.leonte@studio.unibo.it', 'Lucas Antonio', 'Leonte'),
('luigi.linari@studio.unibo.it', 'Luigi', 'Linari'),
('claudio.lodi@studio.unibo.it', 'Claudio', 'Lodi'),
('sebastiano.lucarelli@studio.unibo.it', 'Sebastiano', 'Lucarelli'),
('jonathan.lupini@studio.unibo.it', 'Jonathan', 'Lupini'),
('nicholas.magi@studio.unibo.it', 'Nicholas', 'Magi'),
('davideandrea.magyari@studio.unibo.it', 'Davide Andrea', 'Magyari'),
('martina.malagoli4@studio.unibo.it', 'Martina', 'Malagoli'),
('matteo.maldini4@studio.unibo.it', 'Matteo', 'Maldini'),
('elia.mami@studio.unibo.it', 'Elia', 'Mami'),
('davide.mancini10@studio.unibo.it', 'Davide', 'Mancini'),
('nicolas.mancini@studio.unibo.it', 'Nicolas', 'Mancini'),
('marco.manfroni@studio.unibo.it', 'Marco', 'Manfroni'),
('federico.mantoni@studio.unibo.it', 'Federico', 'Mantoni'),
('lorenzo.marchegiani@studio.unibo.it', 'Lorenzo', 'Marchegiani'),
('pietro.maretti@studio.unibo.it', 'Pietro', 'Maretti'),
('federico.mariani3@studio.unibo.it', 'Federico', 'Mariani'),
('matilde.mariani3@studio.unibo.it', 'Matilde', 'Mariani'),
('raffaele.marrazzo@studio.unibo.it', 'Raffaele Francesco', 'Marrazzo'),
('alessia.marzano@studio.unibo.it', 'Alessia', 'Marzano'),
('simone.mazzacano2@studio.unibo.it', 'Simone', 'Mazzacano'),
('nicola.mazzotti7@studio.unibo.it', 'Nicola', 'Mazzotti'),
('max.melandri@studio.unibo.it', 'Max', 'Melandri'),
('francesco.meloni6@studio.unibo.it', 'Francesco', 'Meloni'),
('leonardo.meloni@studio.unibo.it', 'Leonardo', 'Meloni'),
('filippo.merlini2@studio.unibo.it', 'Filippo', 'Merlini'),
('alessio.minniti@studio.unibo.it', 'Alessio', 'Minniti'),
('tommaso.miraglia@studio.unibo.it', 'Tommaso Cosimo', 'Miraglia'),
('silvia.mirri@unibo.it', 'Silvia', 'Mirri'),
('matteo.monari6@studio.unibo.it', 'Matteo', 'Monari'),
('marco.mondardini2@studio.unibo.it', 'Marco', 'Mondardini'),
('elena.montalti5@studio.unibo.it', 'Elena', 'Montalti'),
('nicolas.montanari3@studio.unibo.it', 'Nicolas', 'Montanari'),
('andrea.monti24@studio.unibo.it', 'Andrea', 'Monti'),
('mattia.mularoni@studio.unibo.it', 'Mattia', 'Mularoni'),
('arthuristvan.muller@studio.unibo.it', 'Arthur Istvan', 'Muller'),
('vera.murgia@studio.unibo.it', 'Vera', 'Murgia'),
('cristofer.napolitano@studio.unibo.it', 'Cristofer Mattia', 'Napolitano'),
('carlo.nicastro2@studio.unibo.it', 'Carlo Michele', 'Nicastro'),
('tommaso.nori@studio.unibo.it', 'Tommaso', 'Nori'),
('maisam.noumi@studio.unibo.it', 'Maisam', 'Noumi'),
('kelvin.olaiya@unibo.it', 'Kelvin Oluwada Milare Obuneme', 'Olaiya'),
('pietro.olivi2@studio.unibo.it', 'Pietro', 'Olivi'),
('antonio.olmeda@studio.unibo.it', 'Antonio', 'Olmeda'),
('matteo.onofri4@studio.unibo.it', 'Matteo', 'Onofri'),
('sohaib.ouakani@studio.unibo.it', 'Sohaib', 'Ouakani'),
('federico.panzavolta@studio.unibo.it', 'Federico', 'Panzavolta'),
('luca.pasini14@studio.unibo.it', 'Luca', 'Pasini'),
('filippo.patrignani2@studio.unibo.it', 'Filippo', 'Patrignani'),
('giovanni.perreon@studio.unibo.it', 'Giovanni', 'Perreon'),
('leonardo.perretta2@studio.unibo.it', 'Leonardo', 'Perretta'),
('marco.pertegato@studio.unibo.it', 'Marco', 'Pertegato'),
('francesco.petrassi2@studio.unibo.it', 'Francesco', 'Petrassi'),
('andrew.pierpaolini@studio.unibo.it', 'Andrew', 'Pierpaolini'),
('stefano.pinza@studio.unibo.it', 'Stefano', 'Pinza'),
('ilaria.piras2@studio.unibo.it', 'Ilaria', 'Piras'),
('lucia.pola@studio.unibo.it', 'Lucia', 'Pola'),
('alessandro.porcheddu@studio.unibo.it', 'Alessandro', 'Porcheddu'),
('mattia.pozzati3@studio.unibo.it', 'Mattia', 'Pozzati'),
('francesco.prandini3@studio.unibo.it', 'Francesco', 'Prandini'),
('maddalena.prandini@studio.unibo.it', 'Maddalena', 'Prandini'),
('lorenzo.prati3@studio.unibo.it', 'Lorenzo', 'Prati'),
('lucas.prati@studio.unibo.it', 'Lucas', 'Prati'),
('luca.pulga@studio.unibo.it', 'Luca', 'Pulga'),
('alessio.pulzoni@studio.unibo.it', 'Alessio', 'Pulzoni'),
('kangzhe.qiu@studio.unibo.it', 'Kangzhe', 'Qiu'),
('cristian.qorri@studio.unibo.it', 'Cristian', 'Qorri'),
('thirumavija.ramasamy@studio.unibo.it', 'Thirumavijayane', 'Ramasamy'),
('vincentrey.ramos@studio.unibo.it', 'Vincent Rey', 'Ramos'),
('gabriele.ranzari@studio.unibo.it', 'Gabriele', 'Ranzari'),
('giovannimaria.rava@studio.unibo.it', 'Giovanni Maria', 'Rava'),
('alessandro.ravaioli8@studio.unibo.it', 'Alessandro', 'Ravaioli'),
('martina.ravaioli6@studio.unibo.it', 'Martina', 'Ravaioli'),
('adampaolo.razzino@studio.unibo.it', 'Adam Paolo', 'Razzino'),
('alessandro.rebosio@studio.unibo.it', 'Alessandro', 'Rebosio'),
('andrea.reggiani14@studio.unibo.it', 'Andrea', 'Reggiani'),
('nicholas.ricci3@studio.unibo.it', 'Nicholas', 'Ricci'),
('filippo.ricciotti@studio.unibo.it', 'Filippo', 'Ricciotti'),
('sofia.ricupero@studio.unibo.it', 'Sofia', 'Ricupero'),
('valentina.rigato@studio.unibo.it', 'Valentina', 'Rigato'),
('mattia.rocchi2@studio.unibo.it', 'Mattia', 'Rocchi'),
('davide.rossi47@studio.unibo.it', 'Davide', 'Rossi'),
('lorenzo.rossi50@studio.unibo.it', 'Lorenzo', 'Rossi'),
('matteo.sacchetti4@studio.unibo.it', 'Matteo', 'Sacchetti'),
('francesco.sacripante@studio.unibo.it', 'Francesco', 'Sacripante'),
('jonathan.salvetti@studio.unibo.it', 'Jonathan', 'Salvetti'),
('patricia.sanchez4@studio.unibo.it', 'Patricia', 'Sánchez Lomas'),
('matteo.santarelli6@studio.unibo.it', 'Matteo', 'Santarelli'),
('valerii.sargov@studio.unibo.it', 'Valerii', 'Sargov'),
('rebecca.scarcelli@studio.unibo.it', 'Rebecca', 'Scarcelli'),
('edoardo.scorza@studio.unibo.it', 'Edoardo', 'Scorza'),
('yue.shen@studio.unibo.it', 'Yue', 'Shen'),
('pietro.siboni3@studio.unibo.it', 'Pietro', 'Siboni'),
('miriam.sonaglia@studio.unibo.it', 'Miriam', 'Sonaglia'),
('hiba.soufi@studio.unibo.it', 'Hiba', 'Soufi'),
('ettore.spaccini@studio.unibo.it', 'Ettore', 'Spaccini'),
('marcello.spagnoli2@studio.unibo.it', 'Marcello', 'Spagnoli'),
('gianmarco.spinaci3@studio.unibo.it', 'Gianmarco', 'Spinaci'),
('ludovico.spitaleri@studio.unibo.it', 'Ludovico Maria', 'Spitaleri'),
('francesco.stortini@studio.unibo.it', 'Francesco', 'Stortini'),
('sabrina.tassinari@studio.unibo.it', 'Sabrina', 'Tassinari'),
('nicolas.tazzieri@studio.unibo.it', 'Nicolas', 'Tazzieri'),
('tchakoute.odile@studio.unibo.it', 'Odile Bertoise', 'Tchakoute'),
('giada.tedaldi@studio.unibo.it', 'Giada', 'Tedaldi'),
('alessandro.testa9@studio.unibo.it', 'Alessandro', 'Testa'),
('matteo.todeschi2@studio.unibo.it', 'Matteo', 'Todeschi'),
('matteo.tonelli8@studio.unibo.it', 'Matteo', 'Tonelli'),
('caterina.torelli2@studio.unibo.it', 'Caterina', 'Torelli'),
('riccardo.traini3@studio.unibo.it', 'Riccardo', 'Traini'),
('daniele.tramonti2@studio.unibo.it', 'Daniele', 'Tramonti'),
('samuele.trapani@studio.unibo.it', 'Samuele', 'Trapani'),
('gianni.tumedei2@unibo.it', 'Gianni', 'Tumedei'),
('egor.tverdohleb@studio.unibo.it', 'Egor', 'Tverdohleb'),
('luca.valentini2@studio.unibo.it', 'Luca', 'Valentini'),
('tommaso.valeriani@studio.unibo.it', 'Tommaso', 'Valeriani'),
('luca.varalerolla@studio.unibo.it', 'Luca', 'Varale Rolla'),
('carmine.varipapa@studio.unibo.it', 'Carmine', 'Varipapa'),
('elettra.ventura@studio.unibo.it', 'Elettra', 'Ventura'),
('luca.venturi29@studio.unibo.it', 'Luca', 'Venturi'),
('valeria.verde@studio.unibo.it', 'Valeria', 'Verde'),
('davide.vignali4@studio.unibo.it', 'Davide', 'Vignali'),
('sara.visani7@studio.unibo.it', 'Sara', 'Visani'),
('lassejoi.werpers@studio.unibo.it', 'Lasse Joi', 'Werpers'),
('lukasz.wojnicz@studio.unibo.it', 'Lukasz', 'Wojnicz'),
('matteo.zoli7@studio.unibo.it', 'Matteo', 'Zoli');

COMMIT;

-----------------------------------------------------------
--- RECENSIONI

-- ---------------------------------------------------------
-- 1. PULIZIA E CREAZIONE TABELLA DI APPOGGIO
-- ---------------------------------------------------------
DROP TABLE IF EXISTS pool_recensioni_bulk;

CREATE TABLE pool_recensioni_bulk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voto INT,
    titolo VARCHAR(100),
    testo VARCHAR(255)
);

-- ---------------------------------------------------------
-- 2. POPOLAMENTO DEI TEMPLATE (Mix di 1, 2, 3, 4, 5 stelle)
-- ---------------------------------------------------------
INSERT INTO pool_recensioni_bulk (voto, titolo, testo) VALUES
-- 5 STELLE
(5, 'Semplicemente perfetto', 'Cibo squisito, personale gentile e ambiente pulito. Il top.'),
(5, 'La mia mensa preferita', 'Vengo qui ogni giorno e non mi stanco mai. Bravi!'),
(5, 'Qualità altissima', 'Sembra di mangiare al ristorante, non in una mensa.'),
(5, 'Lasagne spaziali', 'Le migliori lasagne di Cesena, provare per credere.'),
(5, 'Pulizia impeccabile', 'Tavoli sempre igienizzati e posate brillanti.'),
(5, 'Super consigliato', 'Prezzi onesti per una qualità davvero sorprendente.'),
(5, 'Personale fantastico', 'Sempre col sorriso, ti migliorano la giornata.'),
(5, 'Veloci e bravi', 'Servizio rapido anche con tanta fila. Organizzazione top.'),
(5, 'Tutto buonissimo', 'Dall antipasto al dolce, non ho trovato difetti.'),
(5, 'Ottimo per studenti', 'Il posto ideale per la pausa pranzo universitaria.'),
(5, 'Cucina casalinga', 'Sapori autentici che ricordano la cucina della nonna.'),
(5, 'Menu vario', 'C è sempre l imbarazzo della scelta, anche per vegetariani.'),
(5, 'Pizza ottima', 'Impasto leggero e ingredienti freschi.'),
(5, 'Dolci super', 'La torta al limone è qualcosa di eccezionale.'),
(5, 'Ambiente accogliente', 'Luci calde e sedie comode, molto rilassante.'),
(5, 'Verdure fresche', 'Si sente che usano prodotti di stagione.'),
(5, 'Porzioni abbondanti', 'Si esce sazi e felici. Rapporto qualità prezzo imbattibile.'),
(5, 'Gestione eccellente', 'Mai visto un errore o un ritardo.'),
(5, 'Il caffè è buono', 'Rarità nelle mense: un espresso fatto bene.'),
(5, 'Sicurezza al top', 'Rispetto delle norme igieniche assoluto.'),

-- 4 STELLE
(4, 'Molto buono', 'Mensa solida, si mangia bene quasi sempre.'),
(4, 'Buona scelta', 'Consigliato per chi vuole un pasto veloce e sano.'),
(4, 'Soddisfatto', 'Qualche volta c è fila, ma il cibo vale l attesa.'),
(4, 'Cibo gustoso', 'Primi piatti ben conditi e secondi teneri.'),
(4, 'Ambiente pulito', 'Niente da dire sulla pulizia, molto curata.'),
(4, 'Personale cordiale', 'Disponibili a spiegare gli ingredienti dei piatti.'),
(4, 'Prezzo giusto', 'In linea con la qualità offerta.'),
(4, 'Ottima posizione', 'Comodissimo per chi studia in centro.'),
(4, 'Piatti leggeri', 'Cucinano bene senza esagerare con i condimenti.'),
(4, 'Brava gestione', 'Scorrevole e funzionale.'),
(4, 'Buona la carne', 'Arrosto tenero e saporito.'),
(4, 'Insalatone ok', 'Fresche e ben assortite.'),
(4, 'Servizio rapido', 'In 10 minuti hai mangiato.'),
(4, 'Meglio della media', 'Sicuramente una delle migliori in zona.'),
(4, 'Ok per pranzo', 'Buona soluzione per spezzare la giornata.'),
(4, 'Tutto ok', 'Esperienza positiva senza particolari lodi o critiche.'),
(4, 'Buoni i contorni', 'Patate al forno molto buone.'),
(4, 'Locale spazioso', 'C è sempre posto a sedere.'),
(4, 'Consigliato', 'Ci tornerei volentieri.'),
(4, 'Variazione menu', 'Apprezzo che cambino spesso le proposte.'),

-- 3 STELLE
(3, 'Nella media', 'Cibo mangiabile, ambiente un po rumoroso.'),
(3, 'Senza infamia', 'Va bene per nutrirsi, ma non aspettatevi miracoli.'),
(3, 'Standard', 'Classica mensa, menu standard e sapori standard.'),
(3, 'Accettabile', 'La pasta era un po scotta, il resto ok.'),
(3, 'Così così', 'Dipende dai giorni, a volte bene a volte meno.'),
(3, 'Prezzi in salita', 'Un po caro per quello che offrono ultimamente.'),
(3, 'Servizio ok', 'Niente di speciale, fanno il loro lavoro.'),
(3, 'Poca scelta veg', 'Poche opzioni per chi non mangia carne.'),
(3, 'Pane gommoso', 'Il pane non era freschissimo oggi.'),
(3, 'Porzioni medie', 'Né troppo né troppo poco.'),
(3, 'Rumoroso', 'Difficile parlare a tavola per il baccano.'),
(3, 'Tiepido', 'Il cibo non era caldissimo.'),
(3, 'Location vecchia', 'Avrebbe bisogno di una rinfrescata.'),
(3, 'Fila lunga', 'Troppa attesa alle casse.'),
(3, 'Voto neutro', 'Esperienza dimenticabile.'),
(3, 'Sufficiente', 'Raggiunge la sufficienza ma si può migliorare.'),
(3, 'Menu ripetitivo', 'Sempre le stesse cose il martedì.'),
(3, 'Acqua calda', 'Le bibite non erano fresche.'),
(3, 'Tavoli stretti', 'Si sta un po pigiati.'),
(3, 'Ok per fretta', 'Se hai 15 minuti va bene.'),

-- 2 STELLE
(2, 'Deluso', 'Qualità in netto calo rispetto al passato.'),
(2, 'Non ci siamo', 'Cibo pesante e difficile da digerire.'),
(2, 'Troppo unto', 'Tutto galleggia nell olio.'),
(2, 'Personale freddo', 'Sembra quasi di dare fastidio.'),
(2, 'Cibo insapore', 'Tutto bollito, zero sapore.'),
(2, 'Sconsigliato', 'Meglio un panino al bar.'),
(2, 'Sporco', 'Tavolo appiccicoso e vassoio bagnato.'),
(2, 'Caro', 'Non vale i soldi che chiedono.'),
(2, 'Porzioni misere', 'Sono uscito che avevo ancora fame.'),
(2, 'Freddo', 'Pasta servita fredda di frigo.'),
(2, 'Caos', 'Organizzazione inesistente, tutti che spingono.'),
(2, 'Rumore infernale', 'Impossibile rilassarsi un attimo.'),
(2, 'Carne dura', 'Sembrava una suola di scarpa.'),
(2, 'Verdura stracotta', 'Poltiglia informe.'),
(2, 'Pessimo caffè', 'Acqua sporca.'),
(2, 'Bagni sporchi', 'Igiene dei servizi lascia a desiderare.'),
(2, 'Attesa infinita', 'Servizio lentissimo.'),
(2, 'Menu triste', 'Scelta poverissima.'),
(2, 'Non tornerò', 'Prima e ultima volta.'),
(2, 'Esperienza negativa', 'Da evitare se possibile.'),

-- 1 STELLA
(1, 'Terribile', 'Ho trovato un capello nel piatto. Schifo.'),
(1, 'Mai più', 'Sono stato male dopo aver mangiato qui.'),
(1, 'Evitate!', 'Il peggior posto di sempre.'),
(1, 'Vergognoso', 'Sporcizia ovunque e cibo avariato.'),
(1, 'Soldi buttati', 'Immangiabile, ho lasciato tutto.'),
(1, 'Pessimo', 'Personale maleducato che urla.'),
(1, 'Orrore', 'Odore di fritto rancido che ti rimane addosso.'),
(1, 'Disastro', 'Tutto sbagliato, dal servizio al conto.'),
(1, 'Inaccettabile', 'Pasta cruda e sugo acido.'),
(1, 'Da chiudere', 'Non so come faccia ad essere aperto.'),
(1, 'Zero igiene', 'Ho visto cose in cucina da brividi.'),
(1, 'Scortesia totale', 'Trattati malissimo alla cassa.'),
(1, 'Prezzi folli', 'Rapina per cibo scadente.'),
(1, 'Incubo', 'Un esperienza da dimenticare.'),
(1, 'Schifoso', 'Bicchieri sporchi con rossetto di altri.'),
(1, 'Statene alla larga', 'Non entrateci.'),
(1, 'Imbarazzante', 'Servire avanzi riscaldati è un insulto.'),
(1, 'Bleah', 'Solo a pensarci mi viene la nausea.'),
(1, 'Pericoloso', 'Rischio intossicazione alimentare.'),
(1, 'Sotto zero', 'Il voto giusto sarebbe zero stelle.'),

-- 5 STELLE (20 template)
(5, 'Un sogno per gli studenti', 'Cibo che non ti aspetti in una mensa. Qualità eccelsa.'),
(5, 'Sapori di casa', 'Il ragù è identico a quello che fa mia madre, incredibile.'),
(5, 'Organizzazione top', 'Coda smaltita in 3 minuti cronometrati. Fenomenali.'),
(5, 'Sempre al massimo', 'Vengo qui da tre anni e non sono mai rimasto deluso.'),
(5, 'Opzioni salutari', 'Ottimo per chi vuole mangiare sano senza rinunciare al gusto.'),
(5, 'Staff incredibile', 'Ti accolgono col sorriso, gentilezza d’altri tempi.'),
(5, 'Pulizia chirurgica', 'Si potrebbe mangiare sul pavimento da quanto è pulito.'),
(5, 'Rapporto qualità-prezzo', 'Con il prezzo di un caffè mangi un pasto completo.'),
(5, 'Innovazione costante', 'Ogni settimana trovo piatti nuovi e originali.'),
(5, 'Ingredienti premium', 'Si vede che non risparmiano sulla materia prima.'),
(5, 'Ambiente sereno', 'Perfetto per staccare dallo stress delle lezioni.'),
(5, 'Cotture perfette', 'Carne tenerissima e pasta sempre al dente.'),
(5, 'Miglior pesce in città', 'Il filetto di orata era freschissimo, una sorpresa.'),
(5, 'Vasta scelta veg', 'Finalmente un posto che non offre solo insalata ai vegani.'),
(5, 'Frittura magistrale', 'Calamari croccanti e per nulla unti. Bravi!'),
(5, 'Tutto espresso', 'Cucinato al momento davanti ai tuoi occhi.'),
(5, 'Dolci da pasticceria', 'Il tiramisù è il migliore mai mangiato fuori.'),
(5, 'Consigliatissimo', 'Se studi in questo campus, devi venire qui.'),
(5, 'Un’istituzione', 'La certezza di mangiare bene ogni singolo giorno.'),
(5, 'Dieci e lode', 'Non cambierei nulla. Continuate così!'),

-- 4 STELLE (20 template)
(4, 'Molto soddisfacente', 'Cibo di buona qualità e porzioni corrette.'),
(4, 'Ottima alternativa', 'Molto meglio dei soliti panini veloci al bar.'),
(4, 'Servizio efficiente', 'Personale rapido e locale molto ordinato.'),
(4, 'Promosso', 'Tutto bene, peccato solo per la musica un po’ alta.'),
(4, 'Buoni i primi', 'La pasta al forno è la loro specialità assoluta.'),
(4, 'Esperienza positiva', 'Locale moderno e accogliente, cibo ben curato.'),
(4, 'Ideale per il break', 'Veloce, economico e decisamente gustoso.'),
(4, 'Qualità solida', 'Standard elevato, raramente sbagliano qualcosa.'),
(4, 'Bella atmosfera', 'Si sta bene e si mangia meglio della media.'),
(4, 'Variazione menu', 'Apprezzo molto la rotazione dei piatti stagionali.'),
(4, 'Sempre cordiali', 'Il personale ti fa sempre sentire il benvenuto.'),
(4, 'Pizza approvata', 'Impasto digeribile e condimento abbondante.'),
(4, 'Pane ottimo', 'Servono pane fresco di forno ogni giorno.'),
(4, 'Molto pulito', 'Igiene impeccabile in sala e in cucina.'),
(4, 'Porzioni giuste', 'Ti sazi senza appesantirti troppo per la lezione.'),
(4, 'Pranzo completo', 'Primo, secondo e contorno a un prezzo imbattibile.'),
(4, 'Bravi ragazzi', 'Staff giovane, dinamico e molto educato.'),
(4, 'Buona la frutta', 'Sempre fresca e ben presentata.'),
(4, 'Cucina curata', 'Si vede l’attenzione ai dettagli nel piatto.'),
(4, 'Feedback positivo', 'Tornerò sicuramente la prossima settimana.'),

-- 3 STELLE (20 template)
(3, 'Senza pretese', 'Fa il suo dovere ma non aspettatevi alta cucina.'),
(3, 'Un po’ caotico', 'Cibo buono ma troppa gente ammassata.'),
(3, 'Prezzi ok', 'Qualità accettabile per quanto si paga.'),
(3, 'Così così', 'Il primo era buono, il secondo un po’ troppo secco.'),
(3, 'Mensa standard', 'Nulla di diverso dalle altre mense universitarie.'),
(3, 'Porzioni variabili', 'A volte abbondanti, a volte un po’ scarse.'),
(3, 'Nella norma', 'Né eccellente né pessimo. Un 3 politico.'),
(3, 'Poco saporito', 'Cibo un po’ insipido, servirebbe più brio.'),
(3, 'Tempi lunghi', 'Troppa fila per prendere un piatto semplice.'),
(3, 'Location fredda', 'Arredamento un po’ troppo spartano.'),
(3, 'Menu ripetitivo', 'Gira e rigira mangi sempre le stesse cose.'),
(3, 'Vino mediocre', 'Il vino della casa è a malapena bevibile.'),
(3, 'Sufficiente', 'Raggiunge il 6 ma con poco sforzo.'),
(3, 'Ambiente rumoroso', 'Difficile chiacchierare senza urlare.'),
(3, 'Pasticcio', 'Hanno scambiato il mio ordine con un altro.'),
(3, 'Mediocre', 'Carne un po’ gommosa oggi.'),
(3, 'Da migliorare', 'Potrebbero aggiungere più opzioni di pesce.'),
(3, 'Senza infamia', 'Un pranzo onesto per chi non ha tempo.'),
(3, 'Caffè amaro', 'Qualità del caffè da rivedere.'),
(3, 'Voto medio', 'Un posto come tanti altri.'),

-- 2 STELLE (20 template)
(2, 'Delusione', 'Mi aspettavo molto di meglio viste le recensioni.'),
(2, 'Cibo pesante', 'Faccio fatica a digerire quanto mangiato oggi.'),
(2, 'Troppo unto', 'La pasta galleggiava letteralmente nell olio.'),
(2, 'Servizio freddo', 'Personale che sembra odiare il proprio lavoro.'),
(2, 'Prezzi alti', 'Senza sconti studenti sarebbe un furto.'),
(2, 'Non ci siamo', 'Piatti arrivati freddi al tavolo.'),
(2, 'Qualità in calo', 'Una volta si mangiava molto meglio qui.'),
(2, 'Ambiente sporco', 'Briciole ovunque e tavoli non sparecchiati.'),
(2, 'Scarso impegno', 'Presentazione del piatto imbarazzante.'),
(2, 'Poca igiene', 'Visto il cuoco toccarsi i capelli mentre serviva.'),
(2, 'Pane vecchio', 'Il pane era chiaramente di ieri, duro e secco.'),
(2, 'Acqua calda', 'Bevande dal distributore caldissime.'),
(2, 'Pasta scotta', 'Sembrava colla, immangiabile.'),
(2, 'Poca scelta', 'Se arrivi alle 13:30 è rimasto solo il riso in bianco.'),
(2, 'Vassoio bagnato', 'Tutto appiccicoso, poco piacevole.'),
(2, 'Sapore di chimico', 'Salse che sanno solo di conservanti.'),
(2, 'Personale sgarbato', 'Mi hanno risposto male per una domanda.'),
(2, 'Troppo fritto', 'Odore di olio rancido in tutta la sala.'),
(2, 'Menu noioso', 'Sempre la stessa solfa ogni settimana.'),
(2, 'Meglio evitare', 'Andate altrove se potete.'),

-- 1 STELLA (20 template)
(1, 'Esperienza pessima', 'Trovato un pezzo di ferro nella pasta.'),
(1, 'Mai più!', 'Mal di pancia per due giorni dopo il pranzo.'),
(1, 'Vergognoso', 'Sporco, caro e cibo di qualità infima.'),
(1, 'Inaccettabile', 'Personale che urla contro i clienti.'),
(1, 'Da denuncia', 'Igiene che grida vendetta.'),
(1, 'Schifoso', 'Odore di marcio vicino al bancone.'),
(1, 'Pessimo sotto ogni aspetto', 'Niente si salva in questo posto.'),
(1, 'Soldi buttati', 'Ho dovuto buttare tutto nel cestino.'),
(1, 'Orribile', 'Carne con un colore decisamente sospetto.'),
(1, 'Statene alla larga', 'Non entrateci nemmeno per sbaglio.'),
(1, 'Imbarazzante', 'Servire cibo bruciato è una mancanza di rispetto.'),
(1, 'Incubo universitario', 'Il peggior posto dove abbia mai mangiato.'),
(1, 'Sgarbati e sporchi', 'Un mix letale, sconsigliatissimo.'),
(1, 'Bleah', 'Non ho parole per descrivere lo schifo.'),
(1, 'Disastro totale', 'Organizzazione nulla e cibo pessimo.'),
(1, 'Truffa', 'Prezzi da ristorante per avanzi riscaldati.'),
(1, 'Non a norma', 'Sicurezza alimentare inesistente.'),
(1, 'Una stella è troppo', 'Se potessi darei zero.'),
(1, 'Terribile', 'Cibo crudo e servizio inesistente.'),
(1, 'Evitate assolutamente', 'Rischiate la salute qui.'),

-- 5 STELLE (20 template)
(5, 'Un raggio di sole', 'Mangiare qui mette il buon umore, tutto squisito.'),
(5, 'Qualità da agriturismo', 'Ingredienti genuini e sapori veri. Una rarità.'),
(5, 'Il paradiso del gusto', 'Non cambierei questa mensa con nessun ristorante.'),
(5, 'Efficienza svizzera', 'Coda lunghissima ma smaltita in un baleno. Grandi!'),
(5, 'Sempre sul pezzo', 'Menu aggiornato e piatti sempre caldi. Bravi.'),
(5, 'La lasagna definitiva', 'Se amate la lasagna, questo è il vostro posto.'),
(5, 'Staff da premiare', 'Gentilezza e professionalità fuori dal comune.'),
(5, 'Igiene a livelli maniacali', 'Tutto brilla, dalle posate ai vetri. Ottimo.'),
(5, 'Ricarica post-esame', 'Il posto perfetto per riprendersi dopo uno studio matto.'),
(5, 'Pesce freschissimo', 'Venerdì col fritto misto: un appuntamento fisso.'),
(5, 'Pane di forno vero', 'Pane croccante e ancora tiepido, squisito.'),
(5, 'Porzioni da lottatore', 'Esco sempre pienamente soddisfatto.'),
(5, 'Clima perfetto', 'Ambiente fresco d estate e caldo d inverno. Confortevole.'),
(5, 'Caffè degno di nota', 'Finalmente una mensa dove il caffè è buono davvero.'),
(5, 'Pasticceria artigianale', 'I muffin fatti da loro sono una droga.'),
(5, 'Zero sprechi', 'Apprezzo molto la loro politica contro lo spreco alimentare.'),
(5, 'Voto 10 e lode', 'Impossibile trovare un difetto oggi.'),
(5, 'Come a casa', 'L atmosfera è calda e familiare, mi trovo benissimo.'),
(5, 'Prezzo imbattibile', 'Qualità altissima a prezzi per noi studenti.'),
(5, 'Consigliatissimo a tutti', 'Passateci e non ve ne pentirete mai.'),

-- 4 STELLE (20 template)
(4, 'Ottima scoperta', 'Non pensavo si mangiasse così bene qui.'),
(4, 'Piacevole sorpresa', 'Menu variegato e sapori ben bilanciati.'),
(4, 'Servizio con il sorriso', 'Ragazzi molto educati e disponibili.'),
(4, 'Pausa pranzo ideale', 'Veloce, nutriente e decisamente saporito.'),
(4, 'Quasi perfetto', 'Tutto ottimo, mancava solo un po di sale nella pasta.'),
(4, 'Solidità e cortesia', 'Una certezza per chi studia in zona.'),
(4, 'Molto curato', 'Si vede l attenzione nella scelta dei fornitori.'),
(4, 'Ottima varietà veg', 'Molte opzioni vegetariane finalmente saporite.'),
(4, 'Pizza promossa', 'Impasto leggero e ben lievitato.'),
(4, 'Organizzazione valida', 'File ordinate e servizio molto fluido.'),
(4, 'Secondi di carne top', 'L arista era succosa e ben condita.'),
(4, 'Sempre pulito', 'Un piacere sedersi a tavoli così ben tenuti.'),
(4, 'Prezzo onesto', 'Rapporto qualità-prezzo decisamente a favore dello studente.'),
(4, 'Buoni i contorni', 'Verdure grigliate non unte, molto buone.'),
(4, 'Location moderna', 'Ambiente rinnovato e molto luminoso.'),
(4, 'Pasta fresca ottima', 'I tortellini erano davvero buoni oggi.'),
(4, 'Sempre veloci', 'Anche nelle ore di punta non si aspetta molto.'),
(4, 'Frutta di stagione', 'Sempre matura al punto giusto e fresca.'),
(4, 'Molto consigliato', 'Un ottima mensa per la quotidianità.'),
(4, 'Feedback positivo', 'Continuate così, state facendo un ottimo lavoro.'),

-- 3 STELLE (20 template)
(3, 'Senza infamia', 'Un pasto onesto che non delude ma non stupisce.'),
(3, 'Mensa standard', 'Nulla di più e nulla di meno di quello che ti aspetti.'),
(3, 'Un po rumoroso oggi', 'Cibo ok ma troppo baccano in sala.'),
(3, 'Altalenante', 'Ieri ottimo, oggi un po meno. Dipende dallo chef?'),
(3, 'Porzioni medie', 'Sarebbe stato meglio un po più di pasta nel piatto.'),
(3, 'Prezzi aumentati', 'Qualità costante ma il portafoglio piange.'),
(3, 'Sufficiente', 'Fa il suo dovere di sfamare tra una lezione e l altra.'),
(3, 'Poca scelta se arrivi tardi', 'Alle 14 non c è quasi più nulla.'),
(3, 'Pasta un po troppo cotta', 'Sapore buono ma la consistenza non ci siamo.'),
(3, 'Location spartana', 'Arredamento un po datato ma funzionale.'),
(3, 'Così così', 'Accettabile ma i condimenti sono un po pesanti.'),
(3, 'Servizio distratto', 'Hanno dimenticato di darmi le posate.'),
(3, 'Menu ripetitivo', 'Sempre le solite 3 opzioni ogni settimana.'),
(3, 'Sapore neutro', 'Manca un po di carattere nei piatti.'),
(3, 'Acqua poco fresca', 'Il distributore non raffredda bene.'),
(3, 'Ok per la fretta', 'Se hai mezz ora è la soluzione migliore.'),
(3, 'Pane migliorabile', 'A volte è un po gommoso.'),
(3, 'Ambiente caotico', 'Troppa gente e poca ventilazione.'),
(3, 'Voto 6', 'Senza pretese, mangiabile.'),
(3, 'Non male', 'C è di peggio, ma anche di meglio.'),

-- 2 STELLE (20 template)
(2, 'Delusione', 'Ricordavo mangiarsi meglio, oggi non mi è piaciuto.'),
(2, 'Troppa attesa', 'Mezz ora di fila per un primo freddo. No grazie.'),
(2, 'Cibo molto unto', 'Le patatine fritte grondavano olio vecchio.'),
(2, 'Personale sgarbato', 'Poca cortesia verso gli studenti.'),
(2, 'Prezzi fuori mercato', 'Troppo caro per essere una mensa universitaria.'),
(2, 'Qualità mediocre', 'Cibo che sa di industriale.'),
(2, 'Non ci siamo proprio', 'Esperienza da non ripetere a breve.'),
(2, 'Ambiente sporco', 'Briciole ovunque e vassoi poco puliti.'),
(2, 'Porzioni ridicole', 'Ho pagato per intero e ho ricevuto metà piatto.'),
(2, 'Sapore di frigo', 'Il contorno sembrava avanzato da ieri.'),
(2, 'Troppo chiasso', 'Impossibile mangiare in pace.'),
(2, 'Carne dura', 'Veramente difficile da masticare.'),
(2, 'Verdure bollite male', 'Troppo acquose e senza sale.'),
(2, 'Pasta collosa', 'Un unico blocco di pasta, pessima.'),
(2, 'Bevande calde', 'Zero refrigerazione per l acqua.'),
(2, 'Sconsigliato', 'Meglio portarsi il pranzo da casa.'),
(2, 'Personale svogliato', 'Servizio lentissimo e senza cura.'),
(2, 'Pane secco', 'Sembrava quello della settimana scorsa.'),
(2, 'Zero fantasia', 'Menu noiosissimo e piatti poco curati.'),
(2, 'Meglio evitare', 'Andate alla mensa accanto se potete.'),

-- 1 STELLA (20 template)
(1, 'Esperienza orribile', 'Ho trovato un insetto nell insalata.'),
(1, 'Mai più!', 'Nausea e mal di stomaco dopo pranzo. Statene alla larga.'),
(1, 'Vergognoso', 'Sporcizia visibile e cibo di pessima qualità.'),
(1, 'Inaccettabile', 'Trattati male dal personale e mangiato peggio.'),
(1, 'Da chiudere subito', 'Igiene inesistente, da ufficio d igiene.'),
(1, 'Schifoso', 'Odore di marcio vicino ai banconi del cibo.'),
(1, 'Soldi buttati', 'Tutto immangiabile, ho buttato via il vassoio intero.'),
(1, 'Pessimo sotto ogni punto', 'Cibo freddo, caro e pure cattivo.'),
(1, 'Disastro totale', 'Nulla si salva, un incubo per ogni studente.'),
(1, 'Imbarazzante', 'Servire avanzi del giorno prima è un insulto.'),
(1, 'Incubo alimentare', 'Statene lontani se tenete alla salute.'),
(1, 'Truffa vera e propria', 'Prezzi assurdi per porzioni da fame.'),
(1, 'Posate sporche', 'C erano residui di cibo sulle forchette "pulite".'),
(1, 'Terribile', 'La carne era cruda all interno e bruciata fuori.'),
(1, 'Una stella è generosa', 'Dovrebbero dare la possibilità di dare zero.'),
(1, 'Sgarbati al massimo', 'Personale che urla e ti mette fretta.'),
(1, 'Puzza di fritto rancido', 'Rimane l odore sui vestiti per tutto il giorno.'),
(1, 'Disgustoso', 'Non ho altre parole per descriverlo.'),
(1, 'Oltre il limite', 'Condizioni igieniche precarie.'),
(1, 'Evitate assolutamente', 'Rischiate solo di star male.');


-- ---------------------------------------------------------
-- 3. INSERIMENTO MASSIVO (2110 Recensioni)
-- ---------------------------------------------------------
-- Generiamo 10 recensioni per ogni utente presente in 'clienti'
-- Usiamo una query annidata nella SELECT per pescare un template casuale in modo sicuro

INSERT INTO `recensioni` (`email`, `id_mensa`, `voto`, `titolo`, `descrizione`, `data_ora`)
SELECT 
    c.email,
    FLOOR(1 + RAND() * 21), -- Mensa Random 1-21
    t.voto,
    t.titolo,
    t.testo,
    -- Data casuale nell'ultimo anno
    DATE_ADD('2025-01-01 12:00:00', INTERVAL FLOOR(RAND() * 30000000) SECOND)
FROM 
    `clienti` c
CROSS JOIN 
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
     UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) AS multiplier
JOIN 
    pool_recensioni_bulk t 
    ON t.id = (FLOOR(1 + RAND() * (SELECT COUNT(*) FROM pool_recensioni_bulk)));

-- ---------------------------------------------------------
-- 4. PULIZIA FINALE
-- ---------------------------------------------------------
DROP TABLE pool_recensioni_bulk;